### ISSUE TITLE
Option to disable 2nd screen

### ISSUE THREAD

**Issue by paddy2k** [mereed/pebbleface-prismclock#1]
I really like the watch face but find the second screen very annoying.
Would it be OK to add a config page to disable the second screen?

**Comment by mereed** [comment]
hi paddy.  i've jus nished rebulding this watchface to support pebble time
[so in colour] as well.  it now will have no second screen but if you
choose to do so you canadd date to the first screen.  here's a brif preview
- i'm tesing now and hope to release may wih pebble time ps. this version
  also supports b&w
  [image: Inline image 1]  [image: Inline image 3]

mark

**Comment by paddy2k** [comment]
Thanks for the update. I'll close the ticket then. Looking forward to the colour version.
